## Deployment playbook goes here.

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Start config.yml with process config file, if not running
  pm2:
    name: config.yml
    config: .circleci/ansible/files/config.yml
    state: started


